name: MysqlEconomyBank
main: net.craftersland.money.Money
version: 1.12.0
website: www.craftersland.net
load: STARTUP
depend: [Vault]
softdepend: [TitleManager]
description: Sign Money Bank System.
api-version: 1.13
commands:
    meb:
        description: The main command.
    bank:
        description: The second command.
permissions:
    MysqlEconomyBank.use:
        description: Allows the use of the MysqlEconomyBank signs.
        default: true
    MysqlEconomyBank.admin:
        description: Allows creating and removing MysqlEconomyBank signs.
        default: op
    MysqlEconomyBank.cmd.balance:
        description: Check bank balance via command
        default: op
    MysqlEconomyBank.cmd.deposit:
        description: Deposit money to your bank via command
        default: op
    MysqlEconomyBank.cmd.withdraw:
        description: Withdraw money to your bank via command
        default: op
    MysqlEconomyBank.cmd.interest:
        description: Check remaining time until next interest.
        default: op